// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cluster_families
IntegerVector cluster_families(NumericVector id, NumericVector fid, NumericVector mid);
RcppExport SEXP _networkR_cluster_families(SEXP idSEXP, SEXP fidSEXP, SEXP midSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fid(fidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mid(midSEXP);
    rcpp_result_gen = Rcpp::wrap(cluster_families(id, fid, mid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_networkR_cluster_families", (DL_FUNC) &_networkR_cluster_families, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_networkR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
