# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cluster families
#'
#' @description Computes a vector of groupings in families based on id, father id, and mother id. No check is done to ensure that the id, fid, and mid actually refere to a proper family structure. References to ids in the fid and mid arguments that are not part of the id vector are considered founders.
#' @param id Numeric vector of ids
#' @param fid Numeric vector of ids of the father
#' @param mid Numeric vector of ids of the mother
#' @return Returns an integer vector giving the family index
#' @author Claus Ekstrom \email{ekstrom@@sund.ku.dk}
#' @keywords manip
#' @examples
#'
#' id <- 1:11
#' fid <- c(NA, NA, 1, 1, NA, 23, 45, 5, 5, 7, NA)
#' mid <- c(NA, NA, 2, 2, 65, NA, 46, 6, 6, 6, NA)
#' cluster_families(id, fid, mid)
#'
#' @export 
cluster_families <- function(id, fid, mid) {
    .Call(`_networkR_cluster_families`, id, fid, mid)
}

#' Cluster families
#'
#' @description Computes a vector of groupings in families based on id, father id, and mother id. No check is done to ensure that the id, fid, and mid actually refere to a proper family structure. References to ids in the fid and mid arguments that are not part of the id vector are considered founders.
#' @param id Numeric vector of ids
#' @param fid Numeric vector of ids of the father
#' @param mid Numeric vector of ids of the mother
#' @return Returns an integer vector giving the family index
#' @author Claus Ekstrom \email{ekstrom@@sund.ku.dk}
#' @keywords manip
#' @examples
#'
#' id <- 1:11
#' fid <- c(NA, NA, 1, 1, NA, 23, 45, 5, 5, 7, NA)
#' mid <- c(NA, NA, 2, 2, 65, NA, 46, 6, 6, 6, NA)
#' cluster_families(id, fid, mid)
#'
#' @export 
kinship <- function(id, fid, mid) {
    .Call(`_networkR_kinship`, id, fid, mid)
}

#' Cluster network
#'
#' @description Identifies cluster in a symmetric, weighted network based on an edgelist. The edgelist should contain positive integers for the node numbers. Sequential node numbers will speed up computations.
#' @param from Integer vector of nodes where the link is from
#' @param to Integer vector of nodes where the link is to
#' @param weight Numeric vector of link weights
#' @param threshold A double indicating the minimum link weight that should be considered. Only weights equal to or greater than the threshold will be considered in the clustering
#' @return Returns an integer vector giving the cluster index for each node
#' @author Claus Ekstrom \email{ekstrom@@sund.ku.dk}
#' @keywords manip
#' @examples
#'
#' aaa <- structure(c(1, 6, 5, 4, 5, 11, 1, 5, 3, 13, 16, 15, 18, 6, 7, 8, 10, 12, 14, 15, 15, 16, 17, 17, 18, 20), .Dim = c(13L, 2L))
#' cluster_network(aaa[,1], aaa[,2], weight=rep(1, nrow(aaa))) 
#'
#' @export 
cluster_network <- function(from, to, weight, threshold = 0) {
    .Call(`_networkR_cluster_network`, from, to, weight, threshold)
}

#' @export
Distances <- function(from, to, weight) {
    .Call(`_networkR_Distances`, from, to, weight)
}

