# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cluster families
#'
#' @description Computes the correlation matrix distance between two correlation matrices
#' @param id Numeric vector of ids
#' @param fid Numeric vector of ids of the father
#' @param mid Numeric vector of ids of the father
#' @return Returns a vector giving the xxxxx
#' zero for equal correlation matrices and unity if they differ to a maximum extent.
#' @author Claus Ekstrom \email{claus@@rprimer.dk}
#' @keywords manip
#' @examples
#'
#' x <- 1:5
#'
cluster_families <- function(id, fid, mid) {
    .Call(`_networkR_cluster_families`, id, fid, mid)
}

